# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WKMM_Zre9qCLPUzkpOBV-WRZmUGX3CiP
"""

import cv2
image = cv2.imread('sample_image.jpg')
cv2.imshow('Image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imwrite('output_image.png', image)